

const students=[

    {
        Name : 'Faisal',
        Age : 50,
        Class : 2,
        Gender : 'Male',
        Location : "Cox's Bazar",
        AdmnissionFees: 100,
    },
    {
        Name : 'Razzak',
        Age : 18,
        Class : 9,
        Gender : 'Male',
        Location : 'Khagrachhari',
        AdmnissionFees: 1000,
    },
    {
        Name : 'Ruble',
        Age : 20,
        Class : 8,
        Gender : 'Male',
        Location : 'Khagrachhari',
        AdmnissionFees: 1200,
    },
    {
        Name : 'Shahab',
        Age : 15,
        Class : 7,
        Gender : 'Male',
        Location : 'Habiganj',
        AdmnissionFees: 1400,
    }, 
    {
        Name : 'Istiak',
        Age : 18,
        Class : 9,
        Gender : 'Male',
        Location : 'Comilla',
        AdmnissionFees: 900,
    },
    {
        Name : 'Reza',
        Age : 22,
        Class : 7,
        Gender : 'Male',
        Location : 'Chittagong',
        AdmnissionFees: 700,
    }, 
    {
        Name : 'Sokina',
        Age : 20,
        Class : 9,
        Gender : 'Female',
        Location : 'Dhaka',
        AdmnissionFees: 1200,
    }, 
    {
        Name : 'Kamal',
        Age : 21,
        Class : 8,
        Gender : 'Male',
        Location : 'Dhaka',
        AdmnissionFees: 200,
    }, 
    {
        Name : 'Jorina',
        Age : 18,
        Class : 7,
        Gender : 'Female',
        Location : 'Dhaka',
        AdmnissionFees: 100,
    }, 
    {
        Name : 'Fultosi',
        Age : 20,
        Class : 8,
        Gender : 'Female',
        Location : 'Comilla',
        AdmnissionFees: 800,
    }, 
    {
        Name : 'Jamal',
        Age : 12,
        Class : 5,
        Gender : 'Male',
        Location : 'Dhaka',
        AdmnissionFees: 900,
    }, 
    {
        Name : 'Fulbanu',
        Age : 14,
        Class : 7,
        Gender : 'Female',
        Location : 'Rangpur',
        AdmnissionFees: 1000,
    }, 
    {
        Name : 'Jabed',
        Age : 16,
        Class : 7,
        Gender : 'Male',
        Location : 'Comilla',
        AdmnissionFees: 500,
    }, 
    {
        Name : 'Rohim',
        Age : 17,
        Class : 5,
        Gender : 'Male',
        Location : 'Rangpur',
        AdmnissionFees: 400,
    }, 
    {
        Name : 'Khalek',
        Age : 27,
        Class : 9,
        Gender : 'Male',
        Location : 'Dhaka',
        AdmnissionFees: 2000,
    }, 
    {
        Name : 'Fulmoti',
        Age : 25,
        Class : 7,
        Gender : 'Female',
        Location : 'Comilla',
        AdmnissionFees: 700,
    }, 
    {
        Name : 'Malek',
        Age : 24,
        Class : 8,
        Gender : 'Male',
        Location : 'Dhaka',
        AdmnissionFees: 600,
    }, 
    {
        Name : 'Ketrina',
        Age : 30,
        Class : 9,
        Gender : 'Female',
        Location : 'Munshiganj',
        AdmnissionFees: 300,
    }, 
    {
        Name : 'Karina',
        Age : 50,
        Class : 12,
        Gender : 'Female',
        Location : 'Comilla',
        AdmnissionFees: 1700,
    }, 
    {
        Name : 'Salman',
        Age : 28,
        Class : 6,
        Gender : 'Male',
        Location : 'Dhaka',
        AdmnissionFees: 1500,
    }, 
    {
        Name : 'Azam',
        Age : 30,
        Class : 9,
        Gender : 'Male',
        Location : 'Comilla',
        AdmnissionFees: 200,
    }, 
    {
        Name : 'Miraz',
        Age : 22,
        Class : 5,
        Gender : 'Male',
        Location : 'Rangpur',
        AdmnissionFees: 50,
    }, 
    {
        Name : 'Taskin',
        Age : 18,
        Class : 7,
        Gender : 'Male',
        Location : 'Chittagong',
        AdmnissionFees: 1000,
    },
    {
        Name : 'Sariful',
        Age : 24,
        Class : 6,
        Gender : 'Male',
        Location : 'Rangpur',
        AdmnissionFees: 700,
    },
    {
        Name : 'Dipika',
        Age : 29,
        Class : 7,
        Gender : 'Female',
        Location : 'Dhaka',
        AdmnissionFees: 1000,
    },
    {
        Name : 'Kitika',
        Age : 21,
        Class : 4,
        Gender : 'Female',
        Location : 'Rangpur',
        AdmnissionFees: 800,
    },
    {
        Name : 'Rinko',
        Age : 40,
        Class : 11,
        Gender : 'Male',
        Location : 'Chittagong',
        AdmnissionFees: 700,
    },
    {
        Name : 'Dinko',
        Age : 23,
        Class : 7,
        Gender : 'Male',
        Location : 'Dhaka',
        AdmnissionFees: 1000,
    },
    {
        Name : 'Jarina',
        Age : 18,
        Class : 7,
        Gender : 'Female',
        Location : 'Female',
        AdmnissionFees: 500,
    },
    {
        Name : 'Labib',
        Age : 20,
        Class : 8,
        Gender : 'Male',
        Location : 'Dhaka',
        AdmnissionFees: 1000,
    },
    

];